use std::{env, fs, path::Path};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("themes.rs");

    let themes_dir = Path::new("themes");
    let mut entries: Vec<String> = Vec::new();

    for entry in fs::read_dir(themes_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "tmTheme") {
            let name = path.file_stem().unwrap().to_string_lossy().to_string();
            // Config values like `theme = "dracula"` use the file stem as the key.
            let key = name.replace('\\', "\\\\").replace('"', "\\\"");
            let path_name = key.clone();
            entries.push(format!(
                r#"    ("{key}", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/themes/{path_name}.tmTheme"))),"#
            ));
        }
    }

    entries.sort();

    let code = format!(
        r#"// @generated by build.rs
pub fn bundled_theme_entries() -> &'static [(&'static str, &'static str)] {{
    &[
{}
    ]
}}
"#,
        entries.join("\n")
    );

    fs::write(&dest, code).unwrap();
    println!("cargo:rerun-if-changed=themes/");
}
