use std::{env, fs, path::Path};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("themes.rs");

    let themes_dir = Path::new("themes");
    let mut entries: Vec<String> = Vec::new();

    for entry in fs::read_dir(themes_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.extension().is_some_and(|e| e == "tmTheme") {
            let name = path.file_stem().unwrap().to_string_lossy().to_string();
            // Register under the raw file stem so config values like
            // `theme = "dracula"` or `theme = "tokyo-night"` resolve correctly.
            // The theme's title/name can be read from the .tmTheme metadata.
            let key = name.replace('\\', "\\\\").replace('"', "\\\"");
            let path_name = key.clone();
            entries.push(format!(
                r#"    ("{key}", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/themes/{path_name}.tmTheme"))),"#
            ));
        }
    }

    entries.sort();

    let code = format!(
        r#"// @generated by build.rs
pub fn load_default_themes(set: &mut syntect::highlighting::ThemeSet) {{
    let default_themes: &[(&str, &str)] = &[
{}
    ];
    for (name, content) in default_themes {{
        let mut cursor = std::io::Cursor::new(content.as_bytes());
        if let Ok(theme) = syntect::highlighting::ThemeSet::load_from_reader(&mut cursor) {{
            set.themes.insert(name.to_string(), theme);
        }}
    }}
}}
"#,
        entries.join("\n")
    );

    fs::write(&dest, code).unwrap();
    println!("cargo:rerun-if-changed=themes/");
}
