Output .github/pages/demos/overview.gif

Source ./.github/vhs/config.tape

# Launch upmd with the DEMO file
Type "upmd DEMO.md"
Enter
Sleep 1s

# Run `ls` command
Type "1"
Sleep 1s
Enter
Sleep 1s

# Run `read` command
Type "2"
Sleep 1s
Enter
Sleep 1s
Type "upmd"
Sleep 0.5s
Enter
Sleep 1s

# Run TUI app (nvim)
Type "3"
Sleep 1s
Enter
Sleep 1s
Type "ff"
Sleep 1s
Type "README"
Enter
Sleep 1s
Down 5
Sleep 1s
Type ":q"
Sleep 1s
Enter
Sleep 1s
